version: 2.1

orbs:
  node: circleci/node@0.0.7

executors:
  default_executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/project

commands:
  run_npm_install_with_cache:
    description: "Run NPM install with cache"
    steps:
      - node/with-cache:
          cache-key: "package-lock.json"
          dir: node_modules
          steps:
            - run:
                name: Run NPM install
                command: npm install

jobs:
  build_and_deploy:
    executor: default_executor
    steps:
      - checkout
      - run_npm_install_with_cache
      - run:
          name: NPM run build
          command: npm run build -- --prefix-paths
      - run:
          name: Deploy to branch gh-pages
          command: |
            git config credential.helper 'cache --timeout=120'
            git config --global user.name $GITHUB_USER_NAME
            git config --global user.email $GITHUB_USER_EMAIL
            git clone $CIRCLE_REPOSITORY_URL release
            cd release
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cp -a ../public/. .
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]" --allow-empty
            git push --quiet https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages

workflows:
  default_workflow:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master